apiVersion: tekton.dev/v1beta1
kind: PipelineRun
metadata:
  generateName: express-sample-app-pipeline-run-
spec:
  serviceAccountName: build-bot
  params:
    - name: source-repo
      value: https://github.com/fahadmunawarjan/express-sample-app
    - name: image-repo
      value: quay.io/fahadrha/express-sample-app
    - name: app-name
      value: express-sample-app
  pipelineRef:
    name: nodejs-pipeline
  workspaces:
    - name: pipeline-shared-data
      volumeClaimTemplate:
        spec:
          accessModes:
            - ReadWriteOnce
          resources:
            requests:
              storage: 1Gi          